config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  resources :profiles 
  resources :events 
  resources :attendances
  
  post "events/subscribe/:id", to: "subscribes#create", as: "subscribes"
  get "events/subscribe/:id", to: "subscribes#free_subscribe", as: "free_subscribe" 
 
  root 'events#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
    after_create_commit :welcome_event_send
 
    belongs_to :user
    belongs_to :event

    def welcome_event_send
        UserMailer.welcome_event_email(self.event, self.user).deliver_now
    end 
end

app/models/event.rb
class Event < ApplicationRecord
      
    validates :title, presence: true, length: { in: 4..140 }
    validates :description, presence: true, length: { in: 20..1000 }
    validates :price,
      presence: true,
      numericality: {
        greater_than_or_equal_to: 0,
        less_than: 1000
      }
    validates :location, presence: true
    validates :duration, presence: true
    validate :is_multiple_of_5
    validates :start_date, presence: true
    validate :date_passed

    has_one_attached :picture
    has_many :attendances
    has_many :users, through: :attendances

    def end_date
        start_date + duration * 60
    end

    def participale?(user)
        users.include?(user)
    end

    def is_free?
        price == 0
    end

    def creator
        User.find(self.admin)
    end

    private
    
    def date_passed
        if start_date.present? && start_date < Date.today
          errors.add(:start_date, "can't be past")
        end
    end

    def is_multiple_of_5
        errors.add(:duration, "has to be a multiple of 5") unless duration % 5 == 0 
    end
end

app/models/profile.rb
class Profile < ApplicationRecord
    belongs_to :user
    has_one_attached :avatar 

    def full_name
        "#{self.first_name} #{self.last_name}"
    end

    def check_privileges!
        redirect_to root_path, notice: "You dont have enough permissions" unless current_user == Profile.find(params[:id]).user
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  after_create :init_profile
  after_create :welcome_send

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile, dependent: :destroy
  has_many :attendances
  has_many :events, through: :attendances

  def init_profile
    self.create_profile!
  end

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
    def index 
        @event = Event.find(params[:id])
        @attendances = @event.users
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  before_action :only_creator, only: [:edit, :update, :destroy]
  
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params.merge(admin: current_user.id))
    @event.errors.full_messages
    if @event.save
    
    redirect_to event_path(id: @event), notice: "Your Event was created"
    else
    render 'new'
    end
  end

  def edit
    @event = Event.find(params[:id]) 
  end

  def update
    @event = Event.find(params[:id])
     if @event.update(event_params) 

      redirect_to id: @event, notice: "Your Event was updated"
    else
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:id])
		@event.destroy
		redirect_to root_path
  end

  private

  def event_params
     params.require(:event).permit(:start_date, :duration, :description, :title, :price, :location, :admin, :picture)
  end

  def only_creator
    event = Event.find(params[:id])
    unless current_user.id == event.admin
      flash[:notice] = "Vous n'êtes pas le créateur de l'évènement => Impossilble de le modifier."
     redirect_to root_path
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :check_privileges!, only: [:show]

  def show
    @profile = Profile.find(params[:id])
    @events = Event.where(admin: current_user.id)
  end

  def new
    @profile = Profile.new
  end

  def create 
    @profile = Profile.new
    if @profile.create(profile_params) 
     redirect_to root_path
   else
     render :new
   end
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])
    if @profile.update(profile_params) 

     redirect_to @profile, notice: "Your profile was updated"
   else
     render :edit
   end
  end

  def destroy 
  end

  private 

  def profile_params 
    params.require(:profile).permit(:first_name, :last_name, :description, :avatar)
  end

  def check_privileges!
    redirect_to root_path, notice: "You dont have enough permissions" unless current_user == Profile.find(params[:id]).user
  end
end

app/controllers/subscribes_controller.rb
class SubscribesController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create, :free_subscribe]
    
    def new
    end

    def create  
        @event = Event.find(params[:id])
    
        @amount = @event.price * 100
    
        customer = Stripe::Customer.create({
          email: params[:stripeEmail],
          source: params[:stripeToken],
        })
      
        charge = Stripe::Charge.create({
          customer: customer.id,
          amount: @amount,
          description: 'Eventbite payment',
          currency: 'eur',
        })
    
        # Création d'une participation d'un user à l'évènement
        @attendance = Attendance.create(stripe_customer_id: customer.id, user: current_user, event: @event)
        
        redirect_to event_path(@event.id)
      
        rescue Stripe::CardError => e
            flash[:error] = e.message
            redirect_to @event
    end

    def free_subscribe
      @event = Event.find(params[:id])
      @attendance = Attendance.create(user: current_user, event: @event)
    
      redirect_to event_path(@event.id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def date(resource)
        resource.to_formatted_s(:long)
    end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
    def free(resource)
        resource.price == 0
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/subscribes_helper.rb
module SubscribesHelper
end

app/views/attendances/index.html.erb
<div class="container">
  <div class="row">
      <h1 class="mt-4 mb-3">Guest list for Event : <%= @event.title %>  <%= link_to "Edit your event", edit_event_path(@event), class: "btn btn-outline-secondary", role: "button" %></h1>
        <% if @attendances.blank? %>
            <h2>You are not guest for this event</h2>
        <% else %>
            <div class="container">
            <table class="table table-bordered">
                <thead class="thead-light">
                <tr>
                    <th scope="col"></th>
                    <th scope="col">First Name:</th>
                    <th scope="col">Last Name:</th>
                    <th scope="col">Email:</th>
                </tr>
                </thead>
                <tbody>
                    <% @attendances.each do |user| %>
                    <tr>
                        <td>
                        <%if user.profile.avatar.attached?%>
                                <%= link_to (image_tag user.profile.avatar.variant(resize: "100x100"), alt: 'picture') %>
                            <%else%>
                                <%= link_to image_tag("default_profile_avatar.png", size: "100x100") %>
                            <%end%>
                        </td>
                        <td><%= user.profile.first_name %></td>
                        <td><%= user.profile.last_name %></td>
                        <td><%= user.email %></td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
            </div>
        <% end %>
  </div>
</div>

app/views/events/_card.html.erb
<div class="col-sm-6 col-lg-3 mt-3">
    <div class="card card-cascade narrower">
        <div class="embed-responsive embed-responsive-16by9">
                <%if resource.picture.attached?%>
                    <%= link_to (image_tag resource.picture, class: "card-img-top embed-responsive-item", alt: 'picture'), event_path(resource.id) %>
                <%else%>
                    <%= link_to image_tag("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTKDGeTN40r8Ai9YE2sejGqQzJO4bMiLXy6aJKpbeSCf8iZYfDD"), event_path(resource.id), {class: "card-img-top embed-responsive-item"} %>
                <%end%>
        </div>
        <div class="card-body">
            <div class="text-muted mb-2">
            <%= date(resource.start_date) %>
            </div>
            <div class="center mb-2">
                <strong><%= resource.title %></strong>
            </div>
            <div>
                <p class="center text-capitalize"><%= resource.location %></p>
            </div> 
        </div> 
    </div>
</div>

app/views/events/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
        <br><br><br>
        <%= form_for @event, url: event_path(params[:id]), method: :put do |f| %>
        <h1 class="h3 mb-3 font-weight-normal text-center">Modification de l'évènement:</h1>
                <div class="field">
                <%= f.label :start_date, "Date:"  %><br />
                <%= f.text_field :start_date, class: "form-control" %>
                </div>
                <div class="field">
                <%= f.label :duration, "Durée:" %><br />
                <%= f.text_field :duration, class: "form-control" %>
                </div>
                <div class="field">
                <%= f.label :description, "Description:" %><br />
                <%= f.text_area :description, class: "form-control" %>
                </div>
                <div class="field">
                <%= f.label :title, "Intitulé:" %><br />
                <%= f.text_field :title, class: "form-control" %>
                </div>
                <div class="field">
                <%= f.label :price, "Prix:" %><br />
                <%= f.text_field :price, class: "form-control" %>
                </div>
                <div class="field">
                <%= f.label :location, "Localité:" %><br />
                <%= f.text_field :location, class: "form-control" %>
                </div>   
                <%= f.label :download_image %>
                <%= f.file_field :picture %>
                <div class="actions mt-5">
                <p> <%= f.submit "Modifier", class: "btn btn-lg btn-primary btn-block" %> <%= link_to 'Delete the event', event_path(id: @event), method: :delete, data: { confirm: 'Are you sure?' } %> </p>
                </div>                
        <% end %>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<%= render 'layouts/banner' %>
    <div class="container">
        <div class="row">
            <% @events.each do |event| %>
                <%= render 'card', resource: event %>
            <% end %>
        </div>
    </div>
</div>

app/views/events/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
        <br><br><br>
        <%= form_for @event, url: events_path, method: :post do |f| %>
        <%= render partial: "layouts/error", locals: { resource: @event } %>
        <h1 class="h3 mb-3 font-weight-normal text-center">New Event:</h1>
                <div class="field">
                <%= f.label :start_date, "Date:"  %><br />
                <%= f.text_field :start_date, class: "form-control" %>
                </div>
                <div class="field">
                <%= f.label :duration, "Durée:" %><br />
                <%= f.text_field :duration, class: "form-control" %>
                </div>
                <div class="field">
                <%= f.label :description, "Description:" %><br />
                <%= f.text_area :description, class: "form-control" %>
                </div>
                <div class="field">
                <%= f.label :title, "Intitulé:" %><br />
                <%= f.text_field :title, class: "form-control" %>
                </div>
                <div class="field">
                <%= f.label :price, "Prix:" %><br />
                <%= f.text_field :price, class: "form-control" %>
                </div>
                <div class="field">
                <%= f.label :location, "Localité:" %><br />
                <%= f.text_field :location, class: "form-control" %>
                </div>   
                <%= f.label :upload_image %>
                <%= f.file_field :picture %>
                <div class="actions mt-5">
                <%= f.submit "Créer", class: "btn btn-lg btn-primary btn-block" %>
                </div>                
        <% end %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-8">
        <%if @event.picture.attached?%>
            <%= image_tag @event.picture, class: "card-img-top embed-responsive-item", alt: 'picture' %>
        <% else %>
            <img alt="event picture" src="https://images.unsplash.com/photo-1513151233558-d860c5398176?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80" width="100%">
        <%end%>
        </div>
        <div class="col-4">
        <strong>Lieu&nbsp;: </strong><%= @event.location %><br/>
        <strong>Date&nbsp;: </strong><%= date(@event.start_date) %><br/>
        <strong>Durée&nbsp;: </strong><%= @event.duration %><br/>
        <strong>Prix&nbsp;: </strong><%= @event.price %> €<br/>
        <strong>Organisateur&nbsp;: <%= @event.creator.profile.full_name %></strong><br/><br/>
        <% if current_user %>
            <% if current_user.id == @event.admin %>
                <%= link_to "Mon espace évènement", attendances_path(id: @event), class: "btn btn-secondary"%>
            <% elsif current_user.id == @event.admin || @event.participale?(current_user) %>
                <%= link_to "Tu participe déjà à l'évènement", class: "btn btn-secondary"%>
            <% elsif free(@event) %>
                <%= link_to "Participer à l'évènement", free_subscribe_path(id: @event), class: "btn btn-primary"%>
            <% else %>
                <%= form_tag subscribes_path do %>
                    <article>
                        <% if flash[:error].present? %>
                        <div id="error_explanation">
                            <p><%= flash[:error] %></p>
                        </div>
                        <% end %>
                    </article>
                    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                            data-description="Event subscription"
                            data-amount="<%= @event.price * 100 %>"
                            data-currency="eur"
                            data-locale="auto">
                    </script>
                <% end %>
            <% end %>
        <% else %>
            <%= link_to "Participer à l'évènement", free_subscribe_path(id: @event), class: "btn btn-primary"%>
        <% end %>  
        </div>
    </div>
    <div class="row mt-3 type-event text-primary">
        <div class="col-md-8">
            <h3><%= @event.title %></h3>
            <i class="fas fa-hamburger mr-2 text-muted" title="Food"></i>
            <i class="fas fa-pizza-slice mr-2 text-muted" title="Food"></i>
            <i class="fas fa-beer mr-2 text-muted" title="Drink"></i>
            <i class="fas fa-music mr-2 text-muted" title="Music"></i>
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-md-8">
            <p><%= @event.description %></p>
        </div>
    </div>
    <div class="row center">
        <div class="col-md-6">
            <h4>
            <a href="#" class="text-info mr-1"><i class="fab fa-instagram"></i></a>
            <a href="#" class="text-info mr-1"><i class="fab fa-facebook-square"></i></a>
            <a href="#" class="text-info mr-1"><i class="fab fa-twitter-square"></i></a>
            </h4>
        </div>
    </div>
</div>

app/views/layouts/_banner.html.erb
<div class="hero mb-5">
    <div>
        <h2>For those who love going out</h2>
        <%= link_to "Create Event", new_event_path, class: "btn btn-primary" %>
    </div>
</div>       

app/views/layouts/_error.html.erb
<% if resource.errors.any? %>
  <div class="alert alert-danger" role="alert" id="error_explanation">
    <h5><%= pluralize(resource.errors.count, "error") %> prohibited this article from being saved:</h5>
 
    <ul>
    <% resource.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="page-footer font-small stylish-color-dark pt-4">

  <!-- Footer Links -->
  <div class="container text-center text-md-left">

    <!-- Grid row -->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-4 mx-auto">

        <!-- Content -->
        <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Footer Content</h5>
        <p>Here you can use rows and columns to organize your footer content. Lorem ipsum dolor sit amet,
          consectetur
          adipisicing elit.</p>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none">

      <!-- Grid column -->
      <div class="col-md-2 mx-auto">

        <!-- Links -->
        <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Links</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!">Link 1</a>
          </li>
          <li>
            <a href="#!">Link 2</a>
          </li>
          <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none">

      <!-- Grid column -->
      <div class="col-md-2 mx-auto">

        <!-- Links -->
        <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Links</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!">Link 1</a>
          </li>
          <li>
            <a href="#!">Link 2</a>
          </li>
          <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none">

      <!-- Grid column -->
      <div class="col-md-2 mx-auto">

        <!-- Links -->
        <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Links</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!">Link 1</a>
          </li>
          <li>
            <a href="#!">Link 2</a>
          </li>
          <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <hr>

  <!-- Call to action -->
  <% unless user_signed_in?%>
  <ul class="list-unstyled list-inline text-center py-2">
    <li class="list-inline-item">
      <h5 class="mb-1">Register for free</h5>
    </li>
    <li class="list-inline-item">
      <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-outline-light" %>
    </li>
  </ul>
  <!-- Call to action -->

  <hr>
  <% end %>
  <!-- Social buttons -->
  <ul class="list-unstyled list-inline text-center">
    <li class="list-inline-item">
      <a class="btn-floating btn-fb mx-1">
        <i class="fab fa-facebook-f"> </i>
      </a>
    </li>
    <li class="list-inline-item">
      <a class="btn-floating btn-tw mx-1">
        <i class="fab fa-twitter"> </i>
      </a>
    </li>
    <li class="list-inline-item">
      <a class="btn-floating btn-gplus mx-1">
        <i class="fab fa-google-plus-g"> </i>
      </a>
    </li>
    <li class="list-inline-item">
      <a class="btn-floating btn-li mx-1">
        <i class="fab fa-linkedin-in"> </i>
      </a>
    </li>
    <li class="list-inline-item">
      <a class="btn-floating btn-dribbble mx-1">
        <i class="fab fa-dribbble"> </i>
      </a>
    </li>
  </ul>
  <!-- Social buttons -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="https://mdbootstrap.com/"> MDBootstrap.com</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

app/views/layouts/_header.html.erb
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light bg-white">
    <%= link_to "Eventbrite", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <%= link_to "Create Event", new_event_path, class: "btn btn-secondary" %> 
    <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
            <% if current_user %>
            <li class="nav-item">
                <%= link_to "Profile", profile_path(current_user.profile), class: "btn btn-outline-secondary space_left_button" %>
            </li>
            <li class="nav-item">
                <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "btn btn-outline-secondary space_left_button" %>            </li>
            </li>
            <% else %>
            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Sign Up / Sign In
            </a>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <%= link_to "Sign Up", new_user_registration_path, class: "dropdown-item" %><br/>
                <%= link_to "Sign In", new_user_session_path, class: "dropdown-item" %>
            </div>
            <% end %>
            </li>
        </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbrite2020</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <% if notice %>
      <div class='alert alert-success p-2'>
        <%= notice %>
      </div>
    <% end %>
    <% if alert %>
      <div class='alert alert-danger p-2'>
        <%= alert %>
      </div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/profiles/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
        <br><br><br>
        <%= form_for @profile, url: profile_path(params[:id]), method: :put do |f| %>
        <h1 class="h3 mb-3 font-weight-normal text-center">Edit your profile infos:</h1>
                <div class="field">
                <%= f.label :first_name  %><br />
                <%= f.text_field :first_name, class: "form-control" %>
                </div>
                <div class="field">
                <%= f.label :last_name %><br />
                <%= f.text_field :last_name, class: "form-control" %>
                </div>
                <div class="field">
                <%= f.label :description, "Description:" %><br />
                <%= f.text_area :description, class: "form-control" %>
                </div>  
                <%= f.label :upload_picture %>
                <%= f.file_field :avatar %>
                <div class="actions mt-5">
                <p> <%= f.submit "edit", class: "btn btn-lg btn-primary btn-block" %> </p>
                </div>                
        <% end %>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<h1>Profiles#new</h1>
<p>Find me in app/views/profiles/new.html.erb</p>

app/views/profiles/show.html.erb
<!-- Page Content -->
<div class="container">
  <h1 class="mt-4 mb-3">Your Profile</h1>   
  <div class="row">
        <div class="col-8">
          <div class="img-responsive img-circle">
            <%if @profile.avatar.attached?%>
                <%= image_tag @profile.avatar.variant(resize: "100x100"), alt: 'picture' %>
            <% else %>
                <img alt="profile picture" src="https://images.unsplash.com/photo-1513151233558-d860c5398176?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80" width="100%">
            <%end%>
          </div>
        </div>
        <div class="col-4">
          <div class="card-body">
              <h5 class="card-title">First name:</h5>
              <p class="card-text"><%= @profile.first_name %></p>
              <h5 class="card-title">Last name:</h5>
              <p class="card-text"><%= @profile.last_name %></p>
              <h5 class="card-title">Description:</h5>
              <p class="card-text"><%= @profile.description %></p>
              <%= link_to "Edit your profile infos", edit_profile_path(@profile), :class => "btn btn-secondary btn-xl text-uppercase js-scroll-trigger"%>
          </div>
          <div class="card-body">
            <h5 class="card-title">E-mail:</h5>
            <p class="card-text"><%= current_user.email %></p><p><%= link_to "Edit email/password", edit_user_registration_path, :class => "btn btn-secondary btn-xl text-uppercase js-scroll-trigger"%></p>
          </div> 
      </div>
  </div> 
  <div class="container">
    <div class="row">
        <h1 class="mt-4 mb-3">Your Event</h1>
          <div class="container">
            <table class="table table-bordered">
              <thead class="thead-light">
                <tr>
                  <th scope="col"></th>
                  <th scope="col">Title</th>
                  <th scope="col">Date</th>
                  <th scope="col">Price</th>
                  <th scope="col"></th>
                </tr>
              </thead>
              <tbody>
                  <% @events.each do |event| %>
                    <tr>
                      <td>
                        <%if event.picture.attached?%>
                              <%= link_to (image_tag event.picture.variant(resize: "100x100"), alt: 'picture'), event_path(event.id) %>
                          <%else%>
                              <%= link_to image_tag("default_profile_avatar.png", size: "100x100"), event_path(event.id) %>
                          <%end%>
                        </td>
                        <td><%= event.title %></td>
                        <td><%= date(event.start_date) %></td>
                        <td><%= event.price %> €</td>
                        <td><%= link_to "Show Event", event_path(event.id), class: "btn btn-secondary btn-xl text-uppercase js-scroll-trigger"%></td>
                    </tr>
                  <% end %>
              </tbody>
            </table>
          </div>
    </div>
  </div>
</div>